import { Composition, Folder, Still } from "remotion";
import { SemaFrameRealityOps, SemaFrameRealityOpsPoster } from "./RealityOpsDemo";
import {
  REALITY_OPS_WORKSPACE_DURATION,
  SemaFrameRealityOpsWorkspace,
} from "./RealityOpsWorkspaceCut";
import {
  REALITY_OPS_PROOF_V2_LANDSCAPE_DURATION,
  REALITY_OPS_PROOF_V2_VERTICAL_DURATION,
  SemaFrameRealityOpsProofV2,
  SemaFrameRealityOpsProofV2English,
  SemaFrameRealityOpsProofV2EnglishPoster,
  SemaFrameRealityOpsProofV2Poster,
  SemaFrameRealityOpsProofV2Vertical,
  SemaFrameRealityOpsProofV2VerticalEnglish,
  SemaFrameRealityOpsProofV2VerticalEnglishPoster,
  SemaFrameRealityOpsProofV2VerticalPoster,
} from "./RealityOpsProofV2";
import { SemaFrameDemo, SemaFramePoster } from "./SemaFrameDemo";
import { SemaFrameShort } from "./SemaFrameShort";
import {
  LIVING_ROOM_PUBLIC_DURATION,
  LIVING_ROOM_PUBLIC_ENGLISH_DURATION,
  SemaFrameLivingRoomPublicDemo,
  SemaFrameLivingRoomPublicDemoEnglish,
  SemaFrameLivingRoomPublicDemoEnglishPoster,
} from "./LivingRoomPublicDemo";
import {
  EMERGENCY_CITY_HERO_DURATION,
  SemaFrameEmergencyCityHero,
  SemaFrameEmergencyCityPoster,
} from "./EmergencyCityHero";
import {
  EMERGENCY_CITY_PROOF_V3_LANDSCAPE_DURATION,
  EMERGENCY_CITY_PROOF_V3_VERTICAL_DURATION,
  EMERGENCY_CITY_PROOF_V4_LANDSCAPE_DURATION,
  EMERGENCY_CITY_PROOF_V4_VERTICAL_DURATION,
  SemaFrameEmergencyCityProofV3,
  SemaFrameEmergencyCityProofV3Poster,
  SemaFrameEmergencyCityProofV3Vertical,
  SemaFrameEmergencyCityProofV3VerticalPoster,
  SemaFrameEmergencyCityProofV4,
  SemaFrameEmergencyCityProofV4English,
  SemaFrameEmergencyCityProofV4EnglishPoster,
  SemaFrameEmergencyCityProofV4EnglishVertical,
  SemaFrameEmergencyCityProofV4EnglishVerticalPoster,
  SemaFrameEmergencyCityProofV4Poster,
  SemaFrameEmergencyCityProofV4Vertical,
  SemaFrameEmergencyCityProofV4VerticalPoster,
} from "./EmergencyCityProofV3";
import {
  REALITY_TWIN_PROOF_V1_LANDSCAPE_DURATION,
  REALITY_TWIN_PROOF_V1_VERTICAL_DURATION,
  SemaFrameRealityTwinProofV1,
  SemaFrameRealityTwinProofV1Poster,
  SemaFrameRealityTwinProofV1Vertical,
  SemaFrameRealityTwinProofV1VerticalPoster,
} from "./RealityTwinProofV1";

export const FPS = 30;

export const RemotionRoot = () => (
  <>
    <Folder name="Launch">
      <Composition
        id="SemaFrameHero"
        component={SemaFrameDemo}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={78 * FPS}
      />
      <Composition
        id="SemaFrameShort"
        component={SemaFrameShort}
        width={1080}
        height={1920}
        fps={FPS}
        durationInFrames={18 * FPS}
      />
      <Still id="SemaFramePoster" component={SemaFramePoster} width={1920} height={1080} />
    </Folder>
    <Folder name="Public-Demos">
      <Composition
        id="SemaFrameEmergencyCityHero"
        component={SemaFrameEmergencyCityHero}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={EMERGENCY_CITY_HERO_DURATION}
      />
      <Still
        id="SemaFrameEmergencyCityPoster"
        component={SemaFrameEmergencyCityPoster}
        width={1920}
        height={1080}
      />
      <Composition
        id="SemaFrameEmergencyCityProofV3"
        component={SemaFrameEmergencyCityProofV3}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={EMERGENCY_CITY_PROOF_V3_LANDSCAPE_DURATION}
      />
      <Composition
        id="SemaFrameEmergencyCityProofV3Vertical"
        component={SemaFrameEmergencyCityProofV3Vertical}
        width={1080}
        height={1920}
        fps={FPS}
        durationInFrames={EMERGENCY_CITY_PROOF_V3_VERTICAL_DURATION}
      />
      <Still
        id="SemaFrameEmergencyCityProofV3Poster"
        component={SemaFrameEmergencyCityProofV3Poster}
        width={1920}
        height={1080}
      />
      <Still
        id="SemaFrameEmergencyCityProofV3VerticalPoster"
        component={SemaFrameEmergencyCityProofV3VerticalPoster}
        width={1080}
        height={1920}
      />
      <Composition
        id="SemaFrameEmergencyCityProofV4"
        component={SemaFrameEmergencyCityProofV4}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={EMERGENCY_CITY_PROOF_V4_LANDSCAPE_DURATION}
      />
      <Composition
        id="SemaFrameEmergencyCityProofV4Vertical"
        component={SemaFrameEmergencyCityProofV4Vertical}
        width={1080}
        height={1920}
        fps={FPS}
        durationInFrames={EMERGENCY_CITY_PROOF_V4_VERTICAL_DURATION}
      />
      <Still
        id="SemaFrameEmergencyCityProofV4Poster"
        component={SemaFrameEmergencyCityProofV4Poster}
        width={1920}
        height={1080}
      />
      <Still
        id="SemaFrameEmergencyCityProofV4VerticalPoster"
        component={SemaFrameEmergencyCityProofV4VerticalPoster}
        width={1080}
        height={1920}
      />
      <Composition
        id="SemaFrameLivingRoomPublicDemo"
        component={SemaFrameLivingRoomPublicDemo}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={LIVING_ROOM_PUBLIC_DURATION}
      />
    </Folder>
    <Folder name="English-Demos">
      <Composition
        id="SemaFrameRealityOpsProofV2English"
        component={SemaFrameRealityOpsProofV2English}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={REALITY_OPS_PROOF_V2_LANDSCAPE_DURATION}
      />
      <Composition
        id="SemaFrameRealityOpsProofV2VerticalEnglish"
        component={SemaFrameRealityOpsProofV2VerticalEnglish}
        width={1080}
        height={1920}
        fps={FPS}
        durationInFrames={REALITY_OPS_PROOF_V2_VERTICAL_DURATION}
      />
      <Still
        id="SemaFrameRealityOpsProofV2EnglishPoster"
        component={SemaFrameRealityOpsProofV2EnglishPoster}
        width={1920}
        height={1080}
      />
      <Still
        id="SemaFrameRealityOpsProofV2VerticalEnglishPoster"
        component={SemaFrameRealityOpsProofV2VerticalEnglishPoster}
        width={1080}
        height={1920}
      />
      <Composition
        id="SemaFrameLivingRoomPublicDemoEnglish"
        component={SemaFrameLivingRoomPublicDemoEnglish}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={LIVING_ROOM_PUBLIC_ENGLISH_DURATION}
      />
      <Still
        id="SemaFrameLivingRoomPublicDemoEnglishPoster"
        component={SemaFrameLivingRoomPublicDemoEnglishPoster}
        width={1920}
        height={1080}
      />
      <Composition
        id="SemaFrameEmergencyCityProofV4English"
        component={SemaFrameEmergencyCityProofV4English}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={EMERGENCY_CITY_PROOF_V4_LANDSCAPE_DURATION}
      />
      <Composition
        id="SemaFrameEmergencyCityProofV4EnglishVertical"
        component={SemaFrameEmergencyCityProofV4EnglishVertical}
        width={1080}
        height={1920}
        fps={FPS}
        durationInFrames={EMERGENCY_CITY_PROOF_V4_VERTICAL_DURATION}
      />
      <Still
        id="SemaFrameEmergencyCityProofV4EnglishPoster"
        component={SemaFrameEmergencyCityProofV4EnglishPoster}
        width={1920}
        height={1080}
      />
      <Still
        id="SemaFrameEmergencyCityProofV4EnglishVerticalPoster"
        component={SemaFrameEmergencyCityProofV4EnglishVerticalPoster}
        width={1080}
        height={1920}
      />
      <Composition
        id="SemaFrameRealityTwinProofV1"
        component={SemaFrameRealityTwinProofV1}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={REALITY_TWIN_PROOF_V1_LANDSCAPE_DURATION}
      />
      <Composition
        id="SemaFrameRealityTwinProofV1Vertical"
        component={SemaFrameRealityTwinProofV1Vertical}
        width={1080}
        height={1920}
        fps={FPS}
        durationInFrames={REALITY_TWIN_PROOF_V1_VERTICAL_DURATION}
      />
      <Still
        id="SemaFrameRealityTwinProofV1Poster"
        component={SemaFrameRealityTwinProofV1Poster}
        width={1920}
        height={1080}
      />
      <Still
        id="SemaFrameRealityTwinProofV1VerticalPoster"
        component={SemaFrameRealityTwinProofV1VerticalPoster}
        width={1080}
        height={1920}
      />
    </Folder>
    <Folder name="RealityOps">
      <Composition
        id="SemaFrameRealityOps"
        component={SemaFrameRealityOps}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={78 * FPS}
      />
      <Composition
        id="SemaFrameRealityOpsWorkspace"
        component={SemaFrameRealityOpsWorkspace}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={REALITY_OPS_WORKSPACE_DURATION}
      />
      <Still
        id="SemaFrameRealityOpsPoster"
        component={SemaFrameRealityOpsPoster}
        width={1920}
        height={1080}
      />
      <Composition
        id="SemaFrameRealityOpsProofV2"
        component={SemaFrameRealityOpsProofV2}
        width={1920}
        height={1080}
        fps={FPS}
        durationInFrames={REALITY_OPS_PROOF_V2_LANDSCAPE_DURATION}
      />
      <Composition
        id="SemaFrameRealityOpsProofV2Vertical"
        component={SemaFrameRealityOpsProofV2Vertical}
        width={1080}
        height={1920}
        fps={FPS}
        durationInFrames={REALITY_OPS_PROOF_V2_VERTICAL_DURATION}
      />
      <Still
        id="SemaFrameRealityOpsProofV2Poster"
        component={SemaFrameRealityOpsProofV2Poster}
        width={1920}
        height={1080}
      />
      <Still
        id="SemaFrameRealityOpsProofV2VerticalPoster"
        component={SemaFrameRealityOpsProofV2VerticalPoster}
        width={1080}
        height={1920}
      />
    </Folder>
  </>
);
